apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpa-operator
rules:
  - verbs:
      - list
      - watch
    apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
      - daemonsets
  - verbs:
      - list
      - watch
      - create
      - delete
    apiGroups:
      - autoscaling.k8s.io
    resources:
      - verticalpodautoscalers
