apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vpa-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vpa-operator
subjects:
  - kind: ServiceAccount
    name: {{ include "vpa-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
